project/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :product_types do
      resources :products
  end

  resources :products do
      resources :comments
  end
  

end

project/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :comment_body,  presence: true
  validates :comment_body, length: { maximum: 50 }
  belongs_to :product
end

project/app/models/product.rb
class Product < ActiveRecord::Base
validates :product_name, :product_description,  presence: true
validates :product_name, length: { maximum: 15 }
validates :product_description, length: { maximum: 100 }
validates :product_name, uniqueness: true
has_many :comments
belongs_to :product_type
end

project/app/models/product_type.rb
class ProductType < ActiveRecord::Base
has_many :products
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @product = Product.find(params[:product_id])
    @comment = Comment.new(comment_params)
    @comment.product = @product

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @product, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :"products/error"}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy  
    @comment = Comment.find(params[:id])  
    @comment.destroy  
  
    redirect_to @comment.product  
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:product_id, :comment_body)
    end
end

project/app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:product_type_name)
    end
end

project/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page]).per(6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :product_description, :product_type_id)
    end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/comments_helper.rb
module CommentsHelper
end

project/app/helpers/product_types_helper.rb
module ProductTypesHelper
end

project/app/helpers/products_helper.rb
module ProductsHelper
end

project/app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
  <strong>Posted 
     <%= time_ago_in_words(comment.created_at) %>
  </strong><br />
<%= comment.comment_body %>
<%= link_to "删除该条评论", [@product, comment], :method => :delete, data: {:confirm => "Are you sure?"} %>
  </p>
<% end %>

project/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :comment_body %><br>
    <%= f.text_area :comment_body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

project/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Comment body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.product %></td>
        <td><%= comment.comment_body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

project/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

project/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @comment.product %>
</p>

<p>
  <strong>Comment body:</strong>
  <%= @comment.comment_body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

project/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

project/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to("登入", '#') %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>产品发布系统 </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="banner">
<h2 align="center">产品发布系统</h2>
</div>
<div id="left-panel">
<%= link_to "显示所有产品",products_path %><br/>
<br/>
<%= link_to "查看产品类型",product_types_path %>
</div>

<div id="main-panel">

<%= yield %>
</div>

<div id="footer">
Copyright George &copy; 2016
</div>

</body>
</html>

project/app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h5>产品类型<h5>
    <%= f.text_field :product_type_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

project/app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>


<table class="table">
  <thead>
    <tr>
      <th>产品类型</th>
      <th>产品</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.product_type_name %></td>
        <td><%= (product_type.products.collect { |product|  product.product_name  }).join(", ") %></td>
        <td><%= link_to '显示', product_type %></td>
        <td><%= link_to '编辑', edit_product_type_path(product_type) %></td>
        <td><%= link_to '删除', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '创建新的产品类型', new_product_type_path %>
<br>

project/app/views/product_types/new.html.erb
<h3>新的产品类型</h3>

<%= render 'form' %>

<%= link_to '返回', product_types_path %>

project/app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>产品类型名称:</strong>
  <%= @product_type.product_type_name %>
</p>

<p>
  <b>该类型的产品有:</b>
  <%= (@product_type.products.collect { |product|  product.product_name  }).join(", ") %>
</p>

<%= link_to '编辑', edit_product_type_path(@product_type) %> |
<%= link_to '返回', product_types_path %>

project/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h5>产品名称:<h5>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <h5>产品描述:<h5>
    <%= f.text_area :product_description %>
  </div>

      <div><%= f.collection_select(:product_type_id, ProductType.all, :id, :product_type_name) %></div>
  
   </br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/products/edit.html.erb
<h1>编辑产品</h1>

<%= render 'form' %>

<%= link_to '显示', @product %> |
<%= link_to '返回', products_path %>

project/app/views/products/error.html.erb
 <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<%= link_to "返回", @product %>
  <% end %>

project/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>产品名称</th>
      <th>产品类型</th>
      <th>产品描述</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.product_name,product %></td>
        <td><%= product.product_type.product_type_name %></td>
        <td><%= product.product_description %></td>
        <td><%= link_to '编辑', edit_product_path(product) %></td>
        <td><%= link_to '删除', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>
<br>
<%= link_to '添加新的产品', new_product_path %>

project/app/views/products/new.html.erb
<h3>新产品</h3>

<%= render 'form' %>

<%= link_to '返回', products_path %>

project/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>产品名称:</strong>
  <%= @product.product_name %>
</p>

<p>
  <b>产品类型:</b>
  <%= @product.product_type.product_type_name if @product.product_type %>
</p>

<p>
  <strong>产品描述:</strong>
  <%= @product.product_description %>
</p>

<%= link_to '编辑', edit_product_path(@product) %> |
<%= link_to '返回', products_path %>

<h3>评论</h3>
<div id="comments">
<%= render :partial => @product.comments %>
</div>

<%= form_for [@product, Comment.new] do |f| %>

  <p>
    <%= f.label :content, "新评论" %> <br />
    <%= f.text_area :comment_body, :rows => 5 %>
  </p>
  <p><%= f.submit "添加评论" %></p>
<% end %>